### ISSUE TITLE
Splunk can not extract timestamp from the logs

### ISSUE THREAD

**Issue by emillg** [auth0-extensions/auth0-logs-to-provider#12]
When sending logs to Splunk Cloud, Splunk was not able to extract the correct timestamp from the "date" field. Is it possible to change the json structure a bit so Splunk can extract the timestamp?
<img width="650" alt="screen shot 2019-02-22 at 21 12 07" src="https://user-images.githubusercontent.com/9568664/53268889-a3810e00-36e7-11e9-8085-4c4b4ab6e908.png">

**Comment by sogeniusio** [comment]
We're you able to resolve this?

**Comment by szakavatott** [comment]
PR opened: https://github.com/auth0-extensions/auth0-logs-to-provider/pull/25
