### ISSUE TITLE
Installation instructions are incorrect

### ISSUE THREAD

**Issue by d60402** [auth0-extensions/auth0-logs-to-provider#13]
readme instructions for installing this extension in the Dashboard are incorrect. See https://auth0.slack.com/archives/C9170558S/p1552583743167500

**Comment by dannypnice** [comment]
Any updates to this would be awesome.

In the mean the workaround I could go for would be to fork and generating/commiting the webtask.json file for testing my own custom provider, however build scripts don't generate a workable repo with instructions even with stuff commited.

Is there an example anywhere of what the existing extensions are pointing at structure wise so I could mimic it and point the url at?

Would my best bet be to mimic the old repos that appear to still work with the current instructions?

**Comment by zxan1285** [comment]
@dannypnice hi. If you want to create your own logging extension, i'd recommend using https://github.com/auth0-extensions/auth0-logs-to-logstash as an example. Extensions from this monorepo cannot be installed as custom. We're updating readme to avoid confusion in the future.
Sorry for the inconvenience.
