### ISSUE TITLE
All the log entries sent to Splunk have the severity of `info`

### ISSUE THREAD

**Issue by ssudaraka** [auth0-extensions/auth0-logs-to-provider#17]
All the log messages that are exported to Splunk seems to be having the severity as info even if the log type belongs to an error related log type. i.e. "fsa"

See the screenshot:
![image](https://user-images.githubusercontent.com/7452912/56344466-1f28a400-61db-11e9-8164-802b73cd0b95.png)

**Comment by ssudaraka** [comment]
I think I was able to figure out what might be causing this issue.
In the `server/lib/senders/splunk.js` file, I can see that we are sending the log entry like this.

```
logs.forEach(function(entry) {
      Logger.send({ message: entry });
    });
```

Since we are not sending the severity with it, the `splunk-logging` library will default to the `info` severity. We can send the severity with the Log entry like this.

```
var severity = // transform log type into the appropriate severity
Logger.send({
    message: entry,
    severity: severity
});
```

See example usage here: https://github.com/splunk/splunk-javascript-logging/blob/master/examples/basic.js on line 41 to 56.

**Comment by mzagel** [comment]
This issue is open since 18 April. Can we expect this issue to be solved any time soon?
