### ISSUE TITLE
[Feature] Log to Fluentd

### ISSUE THREAD

**Issue by jcassee** [auth0-extensions/auth0-logs-to-provider#3]
We are logging to a central server using Fluentd and would like to send Auth0 logs too. Using the [fluent-logger-node](https://github.com/fluent/fluent-logger-node) package, a sender would be reasonably easy to write.

Are you working on new senders (and Fluentd in particular), or would you accept a pull requests?

What is the status of this extension, do you expect it to come out of beta soon? Would it be wiser to just create a new extension based on (for example) the Logstash extension?

**Comment by fyockm** [comment]
@jcassee we are _not_ currently working on any new providers. as you mention, it should be fairly easy to add another one. tbh, this is the first request that I've seen for Fluentd, so it's unlikely that we'd add as an official extension in the near term.

that said, you could fork one of the single repos (e.g. https://github.com/auth0-extensions/auth0-logs-to-loggly), update for Fluentd, and install it as a custom extension for your tenant. See the "+ Create Extension" button on the [Extensions page](https://manage.auth0.com/#/extensions) of your Auth0 Dashboard.

![Extensions Docs](https://cdn2.auth0.com/docs/media/articles/extensions/auth0-provided-extensions.png)

**Comment by fyockm** [comment]
@jcassee sorry, i gave you some bad advice. running `auth0-logs-to-loggly` locally will give an error because of an outdated dependency with `auth0-extensions-cli`. updating to `auth0-extensions-cli@1.0.11` should work better.

or, https://github.com/auth0-extensions/auth0-logs-to-logstash is slightly "fresher", but still has a reference to a slightly older cli version.

**Comment by jcassee** [comment]
@fyockm Thanks! I'm not getting an error in the babel-loader package:
```
ERROR in ./webtask.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: Cannot read property 'babel' of undefined
    at Object.module.exports (/home/joost/Ontwikkeling/GoAbout/auth0-logs-to-fluentd/node_modules/babel-loader/lib/index.js:103:36)
```

Would it be better to take the auth0-logs-to-logstash project as a basis and set the auth0-extensions-cli version to 1.0.11?

Also: do you have some more information about developing extensions? I'm currently going on pattern recognition. For example, I am worried about how to adapt URLs like these: [cdn.auth0.com/extensions/auth0-logs-to-loggly/assets/auth0-logs-to-loggly.ui.<%= assets.version %>.css](https://github.com/auth0-extensions/auth0-logs-to-loggly/blob/e562fb3e755a1892646f7d8d534db8c79ed35ebf/server/routes/html.js#L23)

**Comment by jcassee** [comment]
@fyockm Do you have time to help get the custom extension working, or shall I try through the Auth0 ticket system or community?
