### ISSUE TITLE
Unselected event in settings page is still being logged

### ISSUE THREAD

**Issue by daliborpernica** [auth0-extensions/auth0-logs-to-provider#34]
We are using "Auth0 Logs to Application Insights" extension (v2.1) to import events to application insights. Even if "Failed Silent Auth" event is unselected in settings page it is still being imported in application insights.

![auth0_logimport](https://user-images.githubusercontent.com/22004362/70702248-120e7700-1cce-11ea-8a13-ffdc4fc89f32.png)

**Comment by RichardKnop** [comment]
The same problem happens with. Auth0 Authentication API webhooks.
