### ISSUE TITLE
[Feature] Mixpanel Distinct Id Configuration Option

### ISSUE THREAD

**Issue by austince** [auth0-extensions/auth0-logs-to-provider#7]
For Mixpanel user tracking, it is common to set the distinct id to the full `'{provider}|{id}'`. Can you provide a configuration option that allows for that when processing logs?

Right now this is this is how it is set:
https://github.com/auth0-extensions/auth0-logs-to-provider/blob/e59a6cce441db389d13283b58f19f0025d39feaf/server/lib/senders/mixpanel.js#L57

```js
if (config('MIXPANEL_USE_FULL_DISTINCT_ID')) { // or something
  log.distinct_id = `${log.provider}|${log.user_id}`; 
} else {
  log.distinct_id = log.user_id || log.user_name || log.client_id || log._id; 
}
// a template config would be even better, but would be more dev overhead
```

Without this config option, the logs are almost useless as there is no way to connect the users on the Mixpanel side.

Thank you!

**Comment by austince** [comment]
This is still blocking our usage of this feature @stale @fyockm

**Comment by austince** [comment]
This is still blocking our usage of this feature @Stale @fyockm

**Comment by austince** [comment]
This is still blocking our usage of this feature @Stale @fyockm. Is there a better/ less annoying to you way to keep this open?

**Comment by machuga** [comment]
Hi @austince! Apologies for the delay. We are evaluating whether to add this as we are working on a longer term solution.

**Comment by austince** [comment]
Thanks @machuga! Hope you don't mind if I continue to battle the stalebot to keep this open - let me know if there's a less-bothersome way.

**Comment by machuga** [comment]
Hello again, @austince!

I am copying this issue to our product backlog to ensure that it is considered for future implementations of our new [Log Streaming](https://auth0.com/docs/logs/streams) service. Unfortunately we will not be adding any new functionality to this repository, only bug/security fixes. I'll close this ticket out, but the idea is being kept around.

Thank you for pointing this out and I'm sorry for any inconvenience.

**Comment by austince** [comment]
Hey @machuga, is there anywhere I can track this feature on your backlog? Are you planning to build out integrations for Mixpanel using Log Streaming?
