### ISSUE TITLE
Auth0 Management API responds 400 Bad Request after installation for Application Insights

### ISSUE THREAD

**Issue by alastairs** [auth0-extensions/auth0-logs-to-provider#80]
Logs from each run are as follows:

```plain
checkpoint: null
start: 2021-06-25T16:45:01.348Z
end: null
logsProcessed: 0
error: {"name":"ManagementApiError","code":"Bad Request","message":"Bad Request","status":400}
```

I have tried uninstalling and reinstalling the extension to no avail. The extension's client in Auth0 is correctly authorized for the Management API in the tenant, but it seems like a more fundamental problem with the extension if it's receiving 400 Bad Request responses.

**Comment by AntoineTB** [comment]
Hey @alastairs 
Thanks for the report. I'm currently investigating this bug and will keep you updated.

**Comment by AntoineTB** [comment]
Hey @alastairs 
The issue seems to occur when selecting the blank line in the type filter. Not selecting anything or selecting anything but the blank line should be working fine. If it doesn't work for you please let me know!

Cheers,
Antoine

**Comment by alastairs** [comment]
Hi Antoine, that does seem to have fixed it, thank you for the workaround! Could the blank line be removed from the list, perhaps?

**Comment by AntoineTB** [comment]
Hey there, glad to know this worked for you.
I'm in talk with product managers about this blank line. 
Thanks again for reporting this!
